// <auto-generated />
using System;
using MAVN.Service.BonusCustomerProfile.MsSqlRepositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace MAVN.Service.BonusCustomerProfile.MsSqlRepositories.Migrations
{
    [DbContext(typeof(BonusCustomerProfileContext))]
    [Migration("20200701125628_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("bonus_customer_profile")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("MAVN.Service.BonusCustomerProfile.MsSqlRepositories.Entities.CampaignsContribution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CampaignId")
                        .HasColumnName("campaign_id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CustomerId")
                        .HasColumnName("customer_id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId", "CampaignId");

                    b.ToTable("campaigns_contribution");
                });

            modelBuilder.Entity("MAVN.Service.BonusCustomerProfile.MsSqlRepositories.Entities.CustomerProfile", b =>
                {
                    b.Property<Guid>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("customer_id")
                        .HasColumnType("uuid");

                    b.Property<int>("TotalCampaignsContributedCount")
                        .HasColumnName("total_campaigns_contributed_count")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalHotelReferralStayAmount")
                        .HasColumnName("total_hotel_referral_stay_amount")
                        .HasColumnType("numeric");

                    b.Property<int>("TotalHotelReferralStayCount")
                        .HasColumnName("total_hotel_referral_stay")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalHotelStayAmount")
                        .HasColumnName("total_hotel_stay_amount")
                        .HasColumnType("numeric");

                    b.Property<int>("TotalHotelStayCount")
                        .HasColumnName("total_hotel_stay_count")
                        .HasColumnType("integer");

                    b.Property<int>("TotalOfferToPurchaseByLeadCount")
                        .HasColumnName("total_offer_to_purchases_by_lead_count")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalPropertyPurchasesByLeadAmount")
                        .HasColumnName("total_property_purchases_by_lead_amount")
                        .HasColumnType("numeric");

                    b.Property<int>("TotalPropertyPurchasesByLeadCount")
                        .HasColumnName("total_property_purchases_by_lead_count")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalPurchasedAmount")
                        .HasColumnName("total_purchased_amount")
                        .HasColumnType("numeric");

                    b.Property<int>("TotalReferredEstateLeadsCount")
                        .HasColumnName("total_referred_estate_leads_count")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalReferredEstatePurchasesAmount")
                        .HasColumnName("total_referred_estate_purchases_amount")
                        .HasColumnType("numeric");

                    b.Property<int>("TotalReferredEstatePurchasesCount")
                        .HasColumnName("total_referred_estate_purchases_count")
                        .HasColumnType("integer");

                    b.Property<int>("TotalReferredFriendCount")
                        .HasColumnName("total_referred_friend_count")
                        .HasColumnType("integer");

                    b.Property<int>("TotalReferredPurchaseCount")
                        .HasColumnName("total_referred_purchase_count")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalReferredPurchasedAmount")
                        .HasColumnName("total_referred_purchase_amount")
                        .HasColumnType("numeric");

                    b.HasKey("CustomerId");

                    b.HasIndex("CustomerId")
                        .IsUnique();

                    b.ToTable("customer_profile");
                });
#pragma warning restore 612, 618
        }
    }
}
